[workspace]
resolver = "2"
members = [
  "crates/nuraloumi-core",
  "crates/nuraloumi-render-cairo",
  "crates/nuraloumi-wayland",
  "crates/nuraloumi-providers",
  "crates/nuraloumi-shell",
  "crates/nuraloumi-xtask",
]

[workspace.package]
version = "0.0.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/fkr-0/nuraloumi"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
panic = "abort"

[profile.dev]
incremental = false

[profile.test]
incremental = false
